### ISSUE TITLE
TypeError when loading nut.js in Electron main process

### ISSUE THREAD

**Issue by operand** [s1hofmann/native-ui-toolkit#566]
**Version**
nut.js: 4.0.0
Electron.js: 27.0.2

**Short overview**

I'm trying to include nut.js in the main process of an electron app under development but I get an exception related to nut.js and electron fails to start.

**Issue occurs on**

- [ ] Virtual machine
- [ ] Docker container
- [x] Dev/Host system

**node version**:
18.17.1

**OS type and version**:
MacOS: 14.2.1

**Detailed error description**
I get this exception on starting Electron:

```
App threw an error during load

TypeError: Cannot read properties of undefined (reading 'indexOf')
    at Function.getFileName (webpack://operator/./node_modules/bindings/bindings.js?:178:16)
    at bindings (webpack://operator/./node_modules/bindings/bindings.js?:82:48)
    at eval (webpack://operator/./node_modules/@nut-tree/libnut-darwin/permissionCheck.js?:1:88)
    at ./node_modules/@nut-tree/libnut-darwin/permissionCheck.js (./electron/dist/electron-main.cjs:523:1)
    at __webpack_require__ (./electron/dist/electron-main.cjs:3629:42)
    at eval (webpack://operator/./node_modules/@nut-tree/libnut-darwin/index.js?:3:14)
    at ./node_modules/@nut-tree/libnut-darwin/index.js (./electron/dist/electron-main.cjs:513:1)
    at __webpack_require__ (./electron/dist/electron-main.cjs:3629:42)
    at eval (webpack://operator/./node_modules/@nut-tree/libnut/dist/import_libnut.js?:8:9)
    at ./node_modules/@nut-tree/libnut/dist/import_libnut.js (./electron/dist/electron-main.cjs:574:1)
```

**Full code sample to reproduce**
I don't have a reproducible sample yet, but I am working on narrowing this down to something I can share. Any guidance or thoughts in the meantime are appreciated!

**Additional content**
I'm using webpack to compile the sources (with ts-loader) and nut.js is included in the bundle. I'm importing nut.js using ES6 `import` syntax into the main process. I've tried using `require` also and got the same result.

**Comment by s1hofmann** [comment]
Hi @operand 👋 

I can confirm you that nut.js runs just fine under Electron using TypeScript and Webpack, so I'm highly suspecting the Webpack config to be the problem.

Please just link the repo to check out.

**Comment by operand** [comment]
@s1hofmann thank you. That's helpful to know and I'm betting you're right. I'll post a repo link shortly or a solution if I figure it out.

**Comment by operand** [comment]
@s1hofmann Here's a minimal repo that reproduces the issue - https://github.com/operand/electron-nutjs-sample

Instructions to install/run the app:
```
git clone git@github.com:operand/electron-nutjs-sample.git
cd electron-nutjs-sample
yarn install
yarn webpack # to compile
yarn electron .
```
At this point you should see the same TypeError as above.

**Comment by operand** [comment]
I figured out a workaround. I added this to the root webpack config to treat nutjs as an external dependency and that seemed to do the trick without any other code changes.

```
  externals: {
    '@nut-tree/nut-js': 'commonjs @nut-tree/nut-js'
  }
```

Closing the ticket since I have a solution but I'm not sure if this indicates a problem or if that's expected.

**Comment by s1hofmann** [comment]
Was about to say that. Your WebPack config had no configuration how to deal with native addons, so it tried to bundle them and messed up a few things. Externals are excluded from bundling

**Comment by operand** [comment]
That makes sense. I'm just starting to learn how to use nut.js. Thanks again for the help and for the awesome library!
