### ISSUE TITLE
Focus doesn't seem to always focus properly

### ISSUE THREAD

**Issue by DanielTran3** [s1hofmann/native-ui-toolkit#568]
**Version**
v4.0.0

**Short overview**
When attempting to focus a window, a lot of the time it will just return false and not focus. Even when searching for the window in case it is stale and focusing on that, it will not focus.

**Issue occurs on**

- [ ] Virtual machine
- [ ] Docker container
- [x] Dev/Host system

**node version**:
v21.1.0

**OS type and version**:
Windows 11 Home v10.0.22621 Build 22621

**Detailed error description**
N/A, just doesn't focus

**Full code sample to reproduce**
```
/**
 * Find a window based on the title of the window
 * @param tries The number of attempts to find the window (spaced apart by the default 1s)
 * @param titles A list containing strings that show up in the application title. It will 
 * search for substrings from this list
 * @returns The window if it finds one, null otherwise
 */
async function findWindow(tries: number, ...titles: string[]): Promise<screen.Window> {
  while (tries != 0) {
    let matches = 0;
    let windows = await getWindows();
    for (let window of windows) {
      let windowTitle = await window.title
      for (let title of titles) {
        if (windowTitle.includes(title)) {
          matches += 1;
        }
      }
      if (matches == titles.length) {
        console.log("Window Found");
        return Promise.resolve(window);
      }
    }
    tries--;
    await sleep(sleepTime);
  }
  return Promise.resolve(null);
}

/**
 * Attempts to focus on a window
 * @param tries The number of attempts to find the window (spaced apart by the default 1s)
 * @param window The window to focus on
 * @returns True/false if the window has been focused on
 */
async function focusWindow(tries: number, window: screen.Window): Promise<Boolean> {
  await sleep(sleepTime);
  let focused = await window.focus();
  while (!focused && tries != 0) {
    tries--;
    await sleep(sleepTime);
    focused = await window.focus();
    console.log("Focus: %s", focused);
  }
  return Promise.resolve(focused);
}
```

**Additional content**
- Running this as part of Playwright automation. We have an application that launches another application that is a webview that we automate off of. I start the script, which launches a window, then using the `findWindow` function, looks for the window, then attempts to focus on it with `focusWindow`

**Comment by s1hofmann** [comment]
Hi @DanielTran3 👋 

The focus test on CI runs just fine, so far I haven't noticed this behaviour.
There are some scenarios where the OS does mitigate focusing a window, but without further info I can't say anything about it.

**Comment by DanielTran3** [comment]
It seems to have an issue if when I use nodejs to open a window using `spawn()`, then trying to focus on it after the window is up

**Comment by s1hofmann** [comment]
Ok, over the last couple of days I read more about focus rules on Windows than I initially anticipated, but I think I spotted the problem and also might already have a possible solution. Will need to investigate a bit.

**Comment by s1hofmann** [comment]
@DanielTran3 Please give `@nut-tree/nut-js@next` a try

**Comment by DanielTran3** [comment]
Hmmm, looks like it's still having difficulties focusing. I spawn a Revit window as the application and have it poll to focus, but looks like it still doesn't focus.

I pulled `@nut-tree/nut-js@next` and tried on version: `^4.0.1-next.20240318211618`
```
Could not find Revit instance, starting one...


Window Found

Focusing on Revit window                                                                                                                                                                                                                              

Focus: false


Focus: false


Focus: false

Focus: false


Focus: false
```

**Comment by DanielTran3** [comment]
Also, looks like if I manually focus on the window, it will not say that it has focused, where as on v4.0.0 this was the case

**Comment by s1hofmann** [comment]
@DanielTran3 My own tests regarding window focus have passed the expectations I had given the context of this issue. Please provide the application you’re working with and the exact code how it’s launched so I can investigate properly.

**Comment by DanielTran3** [comment]
I am working in VS Code, using Node v21.1.0 in a Playwright project using Typescript.

This is the code I'm using to launch Autodesk Revit and to try to focus on that window based on the title of the application

```
let sleepTime = 1000;
keyboard.config.autoDelayMs = 10

/**
 * Find a window based on the title of the window
 * @param tries The number of attempts to find the window (spaced apart by the default 1s)
 * @param titles A list containing strings that show up in the application title. It will 
 * search for substrings from this list
 * @returns The window if it finds one, null otherwise
 */
async function findWindow(tries: number, ...titles: string[]): Promise<screen.Window> {
  while (tries != 0) {
    let matches = 0;
    let windows = await getWindows();
    for (let window of windows) {
      let windowTitle = await window.title;
      for (let title of titles) {
        if (windowTitle.includes(title)) {
          matches += 1;
        }
        else {
          break;
        }
      }
      if (matches == titles.length) {
        console.log("Window Found");
        return Promise.resolve(window);
      }
    }
    tries--;
    await sleep(sleepTime);
  }
  return Promise.resolve(null);
}

/**
 * Attempts to focus on a window
 * @param tries The number of attempts to find the window (spaced apart by the default 1s)
 * @param window The window to focus on
 * @returns True/false if the window has been focused on
 */
async function focusWindow(tries: number, window: screen.Window): Promise<Boolean> {
  await sleep(sleepTime);
  let focused = await window.focus();
  while (!focused && tries != 0) {
    tries--;
    await sleep(sleepTime);
    focused = await window.focus();
    console.log("Focus: %s", focused);
  }
  return Promise.resolve(focused);
}

/**
 * Launches the specified project in the specified version of Revit
 * @param revitVersion The version of Revit to launch (from the revit-versions.json file)
 * @param revitProject The Revit project to open (from the revit-projects.json file)
 * @param detach True will keep the Revit application open after the test finishes, false will close it
 * @returns Returns the Revit window
 */
export async function launchRevit(revitVersion: RevitVersion, revitProject: RevitProject, detach: boolean = false): Promise<screen.Window> {
  try {
    // Find the Revit window and if it doesn't exist, then launch Revit
    let revit = await findWindow(3, revitVersion.name, revitProject.revitFilename);
    if (revit == null) {
      console.log("Could not find Revit instance, starting one...");
      spawn(revitVersion.path, [revitProject.path], {detached: detach});
      revit = await findWindow(60, revitVersion.name, revitProject.revitFilename);
    }

    // Focus on the Revit window
    console.log("Focusing on Revit window");
    let windowFocused = await focusWindow(30, revit)
    if (!windowFocused) {
      return Promise.resolve(null);
    }
    revit = await getActiveWindow()
    return Promise.resolve(revit)
  } catch (e) {
    console.log(e)
  }
  return Promise.resolve(null);
}
```

**Comment by s1hofmann** [comment]
@DanielTran3 Judging from your code snippet and given the fact that my test setup looks almost the same,  I can't tell why you're running into problems without a detailed investigation.

If you're interested, feel free to reach out to info@dry.software

**Comment by cihadturhan** [comment]
> I am working in VS Code, using Node v21.1.0 in a Playwright project using Typescript.
> 
> This is the code I'm using to launch Autodesk Revit and to try to focus on that window based on the title of the application
> 
> ```
> let sleepTime = 1000;
> keyboard.config.autoDelayMs = 10
> 
> /**
>  * Find a window based on the title of the window
>  * @param tries The number of attempts to find the window (spaced apart by the default 1s)
>  * @param titles A list containing strings that show up in the application title. It will 
>  * search for substrings from this list
>  * @returns The window if it finds one, null otherwise
>  */
> async function findWindow(tries: number, ...titles: string[]): Promise<screen.Window> {
>   while (tries != 0) {
>     let matches = 0;
>     let windows = await getWindows();
>     for (let window of windows) {
>       let windowTitle = await window.title;
>       for (let title of titles) {
>         if (windowTitle.includes(title)) {
>           matches += 1;
>         }
>         else {
>           break;
>         }
>       }
>       if (matches == titles.length) {
>         console.log("Window Found");
>         return Promise.resolve(window);
>       }
>     }
>     tries--;
>     await sleep(sleepTime);
>   }
>   return Promise.resolve(null);
> }
> 
> /**
>  * Attempts to focus on a window
>  * @param tries The number of attempts to find the window (spaced apart by the default 1s)
>  * @param window The window to focus on
>  * @returns True/false if the window has been focused on
>  */
> async function focusWindow(tries: number, window: screen.Window): Promise<Boolean> {
>   await sleep(sleepTime);
>   let focused = await window.focus();
>   while (!focused && tries != 0) {
>     tries--;
>     await sleep(sleepTime);
>     focused = await window.focus();
>     console.log("Focus: %s", focused);
>   }
>   return Promise.resolve(focused);
> }
> 
> /**
>  * Launches the specified project in the specified version of Revit
>  * @param revitVersion The version of Revit to launch (from the revit-versions.json file)
>  * @param revitProject The Revit project to open (from the revit-projects.json file)
>  * @param detach True will keep the Revit application open after the test finishes, false will close it
>  * @returns Returns the Revit window
>  */
> export async function launchRevit(revitVersion: RevitVersion, revitProject: RevitProject, detach: boolean = false): Promise<screen.Window> {
>   try {
>     // Find the Revit window and if it doesn't exist, then launch Revit
>     let revit = await findWindow(3, revitVersion.name, revitProject.revitFilename);
>     if (revit == null) {
>       console.log("Could not find Revit instance, starting one...");
>       spawn(revitVersion.path, [revitProject.path], {detached: detach});
>       revit = await findWindow(60, revitVersion.name, revitProject.revitFilename);
>     }
> 
>     // Focus on the Revit window
>     console.log("Focusing on Revit window");
>     let windowFocused = await focusWindow(30, revit)
>     if (!windowFocused) {
>       return Promise.resolve(null);
>     }
>     revit = await getActiveWindow()
>     return Promise.resolve(revit)
>   } catch (e) {
>     console.log(e)
>   }
>   return Promise.resolve(null);
> }
> ```

Were you able to find a solution to this? Works fine on mac but fails to focus a previous window on Windows.

For now, I'm Alt+Tab'ing to switch the previous app but this is not a long term solution.

**Comment by s1hofmann** [comment]
All I can add here is that during my tests I didn't notice any problems:

https://share.cleanshot.com/tnYyNrSB
