### ISSUE TITLE
Nutjs does not output correctly on window when using boardkey.type () to output Chinese

### ISSUE THREAD

**Issue by wanglike** [s1hofmann/native-ui-toolkit#569]
I am using the boardkey.type ('你好') of the nutjs library. I output Hello normally on Mac, but output as.} on window. What is the reason for this?

nutjs version:     "@nut-tree/nut-js": "^3.1.2",

**Comment by s1hofmann** [comment]
Hi @wanglike 👋 

Cross-platform unicode support requires a different keyboard plugin: [@nut-tree/bolt](https://nutjs.dev/plugins/bolt).

The default plugin does not support it.

Best regards

Simon
