### ISSUE TITLE
Package no longer supported phin@2.9.3

### ISSUE THREAD

**Issue by adrianpisabarrogarcia** [s1hofmann/native-ui-toolkit#570]
**Short summary**

When installing the dependencies of our electron application, the following message appears:

```
warning @nut-tree/nut-js > jimp > @jimp/plugins > @jimp/plugin-print > load-bmfont > phin@2.9.3: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
```

The electron application belongs to a company, and nut-js is a crucial dependency in our proyect, I am one of the developers and this company tries to keep the dependencies in the package.json updated without any warnings. Do you see in the roadmap of the nut.js project being able to look at it? Thank you very much in advance.

**Desired execution environment / tested on** 

- [x] Virtual machine
- [x] Docker container
- [x] Dev/Host system

**node version**: v20.9.0

**OS type and version**: macOs & Windows (no need)

**Comment by s1hofmann** [comment]
> and nut-js is a crucial dependency in our proyect

If you are using nut.js in a commercial context, it’s crucial to your product and you want support, please reach out to info@dry.software
