### ISSUE TITLE
OCR says it failed to detect text but seemed to detect it with a high confidence best match

### ISSUE THREAD

**Issue by nickthorp1** [s1hofmann/native-ui-toolkit#578]
**Version**
 "dependencies": {
    "@nut-tree/nut-js": "4.0.0",
    "@nut-tree/plugin-ocr": "^2.0.1"
  }
**Short overview**

I am running the following code from the docs:

const {screen, singleWord} = require("@nut-tree/nut-js");
const {configure, LanguageModelType, Language, preloadLanguages} = require("@nut-tree/plugin-ocr");

configure({
    languageModelType: LanguageModelType.BEST
});

screen.config.ocrConfidence = 0.8;

(async () => {
    try {
        await preloadLanguages([Language.English, Language.German]);

        const location = await screen.find(singleWord("nut.js"), {
            providerData: {
                lang: [Language.English, Language.German],
                partialMatch: true,
                caseSensitive: true,
            }
        });
    } catch (e) {
        console.error(e);
    }
})();

I get the following error:
Error: [nut.js] - Error: Searching for word-query-nut.js failed. Reason: 'Error: OCR run failed. Reason: Error: Failed to detect word nut.js with config {"lang":["eng","deu"],"partialMatch":true,"caseSensitive":true}. Best match is nut.js with confidence 0.9223227691650391'
    at ScreenClass.find (/Users/*******/Documents/code/nutzv2/node_modules/@nut-tree/nut-js/dist/lib/screen.class.js:169:27)
    at async /Users/*******Documents/code/nutzv2/index.js:14:26

** I have removed my username

The issue is strange because it seems to dected the text but it is throwing an error?

Perhaps I am implementing this wrong? 

**Issue occurs on**
Local machine which a is new mac M3
- [ ] Virtual machine
- [ ] Docker container
- [ ] Dev/Host system

**node version**:
node v18.19.0 (npm v10.2.3)
**OS type and version**:
MAC OS Sonoma 14.2
**Detailed error description**
Error: [nut.js] - Error: Searching for word-query-nut.js failed. Reason: 'Error: OCR run failed. Reason: Error: Failed to detect word nut.js with config {"lang":["eng","deu"],"partialMatch":true,"caseSensitive":true}. Best match is nut.js with confidence 0.9223227691650391'
    at ScreenClass.find (/Users/*******/Documents/code/nutzv2/node_modules/@nut-tree/nut-js/dist/lib/screen.class.js:169:27)
    at async /Users/*******Documents/code/nutzv2/index.js:14:26
**Full code sample to reproduce**

const {screen, singleWord} = require("@nut-tree/nut-js");
const {configure, LanguageModelType, Language, preloadLanguages} = require("@nut-tree/plugin-ocr");

configure({
    languageModelType: LanguageModelType.BEST
});

screen.config.ocrConfidence = 0.8;

(async () => {
    try {
        await preloadLanguages([Language.English, Language.German]);

        const location = await screen.find(singleWord("nut.js"), {
            providerData: {
                lang: [Language.English, Language.German],
                partialMatch: true,
                caseSensitive: true,
            }
        });
    } catch (e) {
        console.error(e);
    }
})();

**Additional content**

> Please provide any (mandatory) additional data to reproduce the error (Dockerfiles etc.)

**Comment by s1hofmann** [comment]
Hi @nickthorp1 👋 

your facing an error that has been [fixed in release 4.0.0](https://nutjs.dev/migrations/4_0_0)

You’re setting `screen.config.ocrConfidence`, but that override did not work properly in your version of nut.js.

You could try to use the `screen.config.confidence` value for OCR, or upgrade to the versions mentioned in the migration guide.

Let me know if it works out for you.

**Comment by nickthorp1** [comment]
Hi Simon,

Thanks for the quick reply, as I posted I read the migration part on the website:

I have now upgraded to the following versions
 "dependencies": {
    "@nut-tree/nut-js": "^4.0.0",
    "@nut-tree/plugin-ocr": "^2.0.1"
    
    
I have this basic code from the tutorials:
const {screen, singleWord} = require("@nut-tree/nut-js");
const {configure} = require("@nut-tree/plugin-ocr");

(async () => {
    try {
        const location = await screen.find(singleWord("nut"));
    } catch (e) {
        console.error(e);
    }
})();

I am running it and getting the same error:

When I run it the screen it is looking at is the code and it seems to find it. Is there anything I have done here which is in-correct?

(base)*****-MacBook-Pro:nutzv4 *****$ node index
Error: [nut.js] - Error: Searching for word-query-nut failed. Reason: 'Error: OCR run failed. Reason: Error: Failed to detect word nut . Best match is nut with confidence 0.9311042022705078'
    at ScreenClass.find (/Users/********/Documents/code/nutzv4/node_modules/@nut-tree/nut-js/dist/lib/screen.class.js:158:27)
    at async /Users/*********/Documents/code/nutzv4/index.js:6:26
(base) Nicks-MacBook-Pro:nutzv4 nicholasthorp$

**Comment by nickthorp1** [comment]
Thanks for the help Simon, I have got it working by setting the global confidence value with the latest versions 

const {screen, singleWord} = require("@nut-tree/nut-js");
const {configure} = require("@nut-tree/plugin-ocr");

screen.config.confidence = 0.8; 

(async () => {
    try {
        const location = await screen.find(singleWord("nut"));
        console.log(location);
    } catch (e) {
        console.error(e);
    }
})();

**Comment by s1hofmann** [comment]
> Hi Simon,
> 
> Thanks for the quick reply, as I posted I read the migration part on the website:
> 
> I have now upgraded to the following versions "dependencies": { "@nut-tree/nut-js": "^4.0.0", "@nut-tree/plugin-ocr": "^2.0.1"
> 
> I have this basic code from the tutorials: const {screen, singleWord} = require("@nut-tree/nut-js"); const {configure} = require("@nut-tree/plugin-ocr");
> 
> (async () => { try { const location = await screen.find(singleWord("nut")); } catch (e) { console.error(e); } })();
> 
> I am running it and getting the same error:
> 
> When I run it the screen it is looking at is the code and it seems to find it. Is there anything I have done here which is in-correct?
> 
> (base)**_**-MacBook-Pro:nutzv4 _**$ node index Error: [nut.js] - Error: Searching for word-query-nut failed. Reason: 'Error: OCR run failed. Reason: Error: Failed to detect word nut . Best match is nut with confidence 0.9311042022705078' at ScreenClass.find (/Users/**_**_/Documents/code/nutzv4/node_modules/@nut-tree/nut-js/dist/lib/screen.class.js:158:27) at async /Users/*********/Documents/code/nutzv4/index.js:6:26 (base) Nicks-MacBook-Pro:nutzv4 nicholasthorp$

Hi @nickthorp1 👋 

in this example you’re not setting `screen.config.ocrConfidence`, so it uses `screen.config.confidence` as a fallback, which defaults to 0.99
