### ISSUE TITLE
32Bit Electron build create some error

### ISSUE THREAD

**Issue by Akash-Rathore** [s1hofmann/native-ui-toolkit#581]
![Screenshot (156)](https://github.com/nut-tree/nut.js/assets/44320485/b0de5e1d-3b2b-452d-82dd-0bc87a39cef5)
libnut.node is not a valid Win32 application.

**Comment by s1hofmann** [comment]
Hi @Akash-Rathore 👋 

nut.js and its binary modules are not compiled for 32bit architectures.
