### ISSUE TITLE
Clarification on number of users in subscription.

### ISSUE THREAD

**Issue by parikshit-dp** [s1hofmann/native-ui-toolkit#589]
**Short summary**

Hey Simon, 

I wanted to check how the _number of users_ works in your subscription plan. 
For the core package, you mention that only one user can use it. But if I have to run an automation on multiple machines with this software how would it be possible to do it?

**Comment by s1hofmann** [comment]
Hi @parikshit-dp 👋 

One user can access packages on one machine at a time.

Volume discounts are possible, though. See https://nutjs.dev/pricing/custom

So one license would have multiple seats which are managed from a single account

**Comment by s1hofmann** [comment]
@parikshit-dp Anything else I can help you with?

**Comment by parikshit-dp** [comment]
Hey Simon, thanks for the prompt response.
I'll evaluate this and come back. 

Just a suggestion that for the **core package** the pricing to be more open and not be limited to number of users, it limits the capacity to use this package at scale.

**Comment by s1hofmann** [comment]
@parikshit-dp I'm happy to discuss possible options to better fit your needs, feel free to drop a mail!
