### ISSUE TITLE
not word install

### ISSUE THREAD

**Issue by JosiasPereira** [s1hofmann/native-ui-toolkit#591]
I'm trying to install the component in my project but it just doesn't work, it seems like the npm registration has disappeared.

Not Found - GET https://registry.npmjs.org/@nut-tree%2fnut-js - Not found

**Comment by s1hofmann** [comment]
Hi @JosiasPereira 👋 

a series of events has lead to nut.js no longer being publicly available on npm.

Pre-built packages are now only available via the nut.js package registry. Please read [this blog post](https://nutjs.dev/blog/i-give-up) to learn about the reasons for this.

You’ll have to build and package nut.js yourself from sources, or, if you want to have continuous updates and ready-to-use packages, choose a subscription [here](https://nutjs.dev/pricing/pricing).

Best regards 

Simon
