### ISSUE TITLE
Intermittent "No WindowElementInspector registered" Error in @nut-tree/element-inspector

### ISSUE THREAD

**Issue by wooogler** [s1hofmann/native-ui-toolkit#597]
**Version**
@nut-tree/element-inspector: 0.1.6-next.20240531081642

**Short overview**
Attempting to use the getElements method from the @nut-tree/element-inspector/win module results in an intermittent "No WindowElementInspector registered" error.

**Issue occurs on**

- [ ] Virtual machine
- [ ] Docker container
- [X] Dev/Host system

**node version**:
20.14.0

**OS type and version**:
Windows 11 Pro

**Detailed error description**
I purchased a solo plan for nut.js and encountered an issue when using the elements module from @nut-tree/element-inspector/win.

When running the provided code, I intermittently encounter the following error:
```
Error: 2024-06-03T01:55:55.869Z - ERROR - [nut.js] - Error: No WindowElementInspector registered
    at DefaultProviderRegistry.getWindowElementInspector (C:\dev\project\node_modules\.pnpm\@nut-tree+nut-js@4.2.0\node_modules\@nut-tree\nut-js\lib\provider\provider-registry.class.ts:199:19)
    at Window.getElements (C:\dev\project\node_modules\.pnpm\@nut-tree+nut-js@4.2.0\node_modules\@nut-tree\nut-js\lib\window.class.ts:98:34)
    at C:\dev\project\src\ipa\desktopActions.ts:23:38
    at Generator.next (<anonymous>)
    at fulfilled (C:\dev\project\src\ipa\desktopActions.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```
This error sometimes occurs, and sometimes the getElements method works correctly. Rebooting does not seem to resolve the issue consistently.

Additionally, I tried running the application with administrator privileges, but the issue still persists.

I am unsure why this bug occurs and what needs to be reset to resolve it.

**Full code sample to reproduce**
```
import {
  useConsoleLogger,
  ConsoleLogLevel,
  screen,
  windowWithTitle,
} from "@nut-tree/nut-js";
import { useBolt } from "@nut-tree/bolt";
import { elements } from "@nut-tree/element-inspector/win";

useConsoleLogger({ logLevel: ConsoleLogLevel.DEBUG });
useBolt();

async function main() {
  const screens = await screen.findAll(windowWithTitle(/.*/));
  screens.forEach(async (screen) => {
    const title = await screen.title;
    console.log(title);
  });

  const screenTitle = "{specific title}";

  const specificScreen = await screen.find(windowWithTitle(screenTitle));
  await specificScreen.focus();
  const items = await specificScreen.getElements();
  console.log(JSON.stringify(items, null, 2));
}

main();
```

**Additional content**
The environment is the same as the previously reported issue ([GitHub Issue #595](https://github.com/nut-tree/nut.js/issues/595)).

Additionally, I noticed that the current code in the nut.js element-inspector tutorial (https://nutjs.dev/plugins/element-inspector#usage-retrieve-elements-of-a-window) is not wrapped in an async function, which causes it not to work as expected. This might be something to look into as well.

**Comment by s1hofmann** [comment]
Hi @wooogler 👋 

your code is missing an import for `@nut-tree/element-inspector`.

```js
import "@nut-tree/element-inspector";
import {elements} from "@nut-tree/element-inspector/win";
```

In your provided sample you’re only importing the Windows element definition, which does not register the `WindowElementInspector`

**Comment by wooogler** [comment]
Thank you so much!
