### ISSUE TITLE
LICENSE file

### ISSUE THREAD

**Issue by billo32** [s1hofmann/native-ui-toolkit#600]
Hello! I can't find the license information. Could you give more detail information about license? 

What type of open source license project is used? (MIT, Apache, etc?)

Thank you!

**Comment by s1hofmann** [comment]
Hi @billo32 👋 

the license file is located in the core package of nut.js, which got move [here](https://github.com/nut-tree/nut.js/blob/develop/core/nut.js/LICENSE) after switching to a mono repo.

I probably should move it back to root level.
