### ISSUE TITLE
pnpm i @nut-tree/nut-js is 404

### ISSUE THREAD

**Issue by rmstsd** [s1hofmann/native-ui-toolkit#602]
**Version**

**Short overview**

**Issue occurs on**

- [ ] Virtual machine
- [ ] Docker container
- [ ] Dev/Host system

**node version**:

**OS type and version**:

**Detailed error description**

**Full code sample to reproduce**

**Additional content**

> Please provide any (mandatory) additional data to reproduce the error (Dockerfiles etc.)

**Comment by Wissididom** [comment]
It was deleted from NPM. See this blog post: https://nutjs.dev/blog/i-give-up

**Comment by mxlauc** [comment]
this worked for me:
https://www.npmjs.com/package/@nut-tree-fork/nut-js
