### ISSUE TITLE
cannot type special characters

### ISSUE THREAD

**Issue by xiatian12345** [s1hofmann/native-ui-toolkit#604]
**Version**
^4.0.0
**Short overview**
use keyboard.type some special character,cannot get correct result,missing some special character
**node version**:
v18.20.3
**OS type and version**:
window10
**Full code sample to reproduce**
await keyboard.type('@Ω@');//this type the '@@' and 'Ω' is lost

**Comment by s1hofmann** [comment]
Hi @xiatian12345 👋 

there’s a plugin to get full unicode support on all platforms: https://nutjs.dev/plugins/bolt
