### ISSUE TITLE
Window Key Not Working

### ISSUE THREAD

**Issue by Akash-Rathore** [s1hofmann/native-ui-toolkit#605]
I pressed the Windows key and then changed the behavior of the keyboard

**Comment by s1hofmann** [comment]
Hi @Akash-Rathore 👋 

I'm sorry, but I don’t know what to do with this information.
Please fill the issue template with as much detail as possible!

Best regards 

Simon

**Comment by Akash-Rathore** [comment]
I'm trying to install a library using Nut.js, but the Windows key press isn't working.

keyboard.pressKey(Key.LeftWin);

**Comment by s1hofmann** [comment]
Yes, but what’s the context?

Which OS are you using? In which version?
Which node and nut.js version are you on?

What's the expected outcome after pressing the key?

**Comment by Akash-Rathore** [comment]
Operating Systems: Windows 10 and Windows 11.
Nut-tree Version: 4.2.2
Node.js Version: 20

when press 
 keyboard.pressKey(Key.LeftWin);
 
 hang the keyboard
