### ISSUE TITLE
Repo dead?

### ISSUE THREAD

**Issue by smithkyle** [s1hofmann/native-ui-toolkit#606]
I know that the prebuilt/up-to-date packages are behind a paywall now, but the original "resignation" blog post said that this repo would be updated with a delay, subscribers coming first. There have been a number of private releases since then, but none to this repo, so just checking if there eventually will be or not.

Thanks.

**Comment by s1hofmann** [comment]
Hi @smithkyle 👋 

Short answer: It’s not dead.

Longer answer: The releases you mentioned essentially have no real impact on the core repo. On release reverted a change that was introduced one release earlier, another one was done to re-release a broken Windows binary. So effectively no new things have been released which I spared myself some time to move them over

**Comment by smithkyle** [comment]
👍🏻
