### ISSUE TITLE
npm install @nut-tree/nut-js not found

### ISSUE THREAD

**Issue by zmfish** [s1hofmann/native-ui-toolkit#607]
**npm install @nut-tree/nut-js not found**

**vscode electron project**

- [ ] windows

**node version : 18.17.0**:

**I created an electron project and needed to install @nut-tree/nut-js. I clicked the mouse on a specific area within the project, but I encountered an error during installation.**

**Not Found - GET https://registry.npmjs.org/@nut-tree%2fnut-js - Not foun**

**Comment by NiteKik** [comment]
+1

**Comment by s1hofmann** [comment]
Hi @zmfish and @SmallAirplaneX 👋 

please note that nut.js is no longer publicly available on npm: https://github.com/nut-tree/nut.js?tab=readme-ov-file#the-price-of-open-source

**Comment by suqunnvzi** [comment]
使用cnpm
