### ISSUE TITLE
Sending the window handler in the keyboard methods.

### ISSUE THREAD

**Issue by augustnmonteiro** [s1hofmann/native-ui-toolkit#608]
**Short summary**
I need to be able to type in a specific window only, I know that win32 supports sending the window handler in order to do that.
Is it possible to do that window nutJS?

**Comment by s1hofmann** [comment]
Hi @augustnmonteiro 👋 

The way nut.js sends input always targets the window which has input focus.
You’d have to focus the window first, sending input to any background window is not supported.
